/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yanyuanquan_ndkdemo_JNIUtil */

#ifndef _Included_com_yanyuanquan_ndkdemo_JNIUtil
#define _Included_com_yanyuanquan_ndkdemo_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yanyuanquan_ndkdemo_JNIUtil
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yanyuanquan_ndkdemo_JNIUtil_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_yanyuanquan_ndkdemo_JNIUtil
 * Method:    getBitmapByNDK
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yanyuanquan_ndkdemo_JNIUtil_getBitmapByNDK
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
